## YAML Template.
---
name: OLSMonitor
version: 1.3
author: Rocktopod
main: com.rockpartymc.OLSMonitor

commands:
    olsmonitor:
        description: Commands for OLSMonitor.  Alias /olsm
        aliases: [olsm]
        usage: /olsmonitor