## YAML Template.
---
name: SMMonitor
version: 1.3
author: Rocktopod
main: com.rockpartymc.SMMonitor

commands:
    smmonitor:
        description: Commands for SMMonitor.  Alias /smm
        aliases: [smm]
        usage: /smmonitor